version: '3.3'
services:
  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./src/main/resources/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/files:/files

